require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Layout/LineLength:
  Max: 120

RSpec/MultipleExpectations:
  Max: 5

Gemspec/RequiredRubyVersion:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Capybara/RSpec/PredicateMatcher:
  Enabled: false
